[phases.setup]
nixPkgs = ["rust-bin.stable.\"1.88.0\".default", "gcc", "pkg-config", "openssl"]

[phases.build]
cmds = ["cargo build --release && cp target/release/flowfull-rust-starter /app/flowfull-rust-starter"]

[start]
cmd = "./flowfull-rust-starter"
